### ISSUE TITLE
README is missing step 7

### ISSUE THREAD

**Issue by GenericEric** [fm407/PIA-NextGen-PortForwarding#14] opened 2021-04-29 06:37 UTC
Just what the title says. Step 8 refers to staying root like the previous step, but the previous step in the readme is step 6 and it's in the GUI.

**Comment by Hakun1n** [comment] 2021-05-07 21:10
Caused by removal of old step 7. Fixed in #15 , thanks.

**Closed as completed** 2021-07-08 15:31 UTC
Labels: documentation
